[package]
name = "coc-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitmatch = "0.1.1"
siphasher = "0.3.10"
arrayvec = "0.7.2"

[profile.dev]
opt-level = 3

